import type { Listing } from "./types";

const now = Date.now();
const days = (n: number) => new Date(now + n * 86400000).toISOString();
const daysAgo = (n: number) => new Date(now - n * 86400000).toISOString();

export const SEED_LISTINGS: Listing[] = [
  {
    id: "l-001",
    title: "Lycoming O-320 — Fresh Top Overhaul",
    description:
      "O-320-E2D, recent top overhaul with new cylinders, pistons, and rings. All logs available. Priced to sell — must clear hangar space. Ground run video on request.",
    category: "for-sale",
    tags: ["engine", "aircraft"],
    photos: [
      "https://images.unsplash.com/photo-1583149577540-6f7e5edf6770?w=800",
      "https://images.unsplash.com/photo-1581093588401-fbb62a02f120?w=800",
    ],
    status: "active",
    authorId: "1001",
    authorName: "Tom Becker",
    authorEmail: "tom.becker@example.com",
    authorPhone: "+1 555-201-3344",
    authorPhoneVisible: true,
    postedAt: daysAgo(3),
    expiresAt: days(57),
  },
  {
    id: "l-002",
    title: "Wanted: Garmin GTN 650 (any condition)",
    description:
      "Looking for a Garmin GTN 650, working or not. Willing to consider GTN 650Xi or even a non-WAAS unit if priced right. Cash buyer.",
    category: "wanted",
    tags: ["avionics"],
    photos: [],
    status: "active",
    authorId: "1002",
    authorName: "Linda Schwartz",
    authorEmail: "linda.s@example.com",
    authorPhone: null,
    authorPhoneVisible: false,
    postedAt: daysAgo(7),
    expiresAt: days(53),
  },
  {
    id: "l-003",
    title: "Hangar Space Available — KOSH",
    description:
      "Half-hangar T-shelter at Wittman Field available for rent starting next month. Great for a single-engine piston up to ~28 ft wingspan. Power & gravel apron.",
    category: "hangar-space",
    tags: [],
    photos: [
      "https://images.unsplash.com/photo-1517400508447-f8dd518b86db?w=800",
    ],
    status: "active",
    authorId: "1003",
    authorName: "Greg Hollis",
    authorEmail: "greg.hollis@example.com",
    authorPhone: "+1 555-441-9087",
    authorPhoneVisible: true,
    postedAt: daysAgo(1),
    expiresAt: days(59),
  },
  {
    id: "l-004",
    title: "A&P Inspection & Annual Help — Reasonable Rates",
    description:
      "A&P/IA with 22 years experience offering annuals, condition inspections, and pre-buy help for chapter members. Hangar workshop available.",
    category: "services",
    tags: ["sheet-metal", "fabric-covering"],
    photos: [],
    status: "active",
    authorId: "1004",
    authorName: "Marie Chen",
    authorEmail: "marie.chen@example.com",
    authorPhone: "+1 555-883-1122",
    authorPhoneVisible: true,
    postedAt: daysAgo(12),
    expiresAt: days(48),
  },
  {
    id: "l-005",
    title: "Tailwheel Endorsement Training — Citabria",
    description:
      "CFI offering tailwheel endorsements in a 7ECA Citabria. Block rates available for chapter members. Based at our home field.",
    category: "training",
    tags: ["aircraft"],
    photos: [
      "https://images.unsplash.com/photo-1540962351504-03099e0a754b?w=800",
    ],
    status: "active",
    authorId: "1005",
    authorName: "Dan Wilkerson",
    authorEmail: "dan.w@example.com",
    authorPhone: null,
    authorPhoneVisible: false,
    postedAt: daysAgo(20),
    expiresAt: days(40),
  },
  {
    id: "l-006",
    title: "Need help: Welding 4130 motor mount",
    description:
      "Building an RV-7 and need a hand TIG-welding the engine mount tabs. Happy to trade hangar time, lunches, and shop labor.",
    category: "expertise-help",
    tags: ["welding", "kit-build"],
    photos: [],
    status: "active",
    authorId: "1006",
    authorName: "Eric Park",
    authorEmail: "eric.park@example.com",
    authorPhone: "+1 555-700-2010",
    authorPhoneVisible: true,
    postedAt: daysAgo(2),
    expiresAt: days(58),
  },
  {
    id: "l-007",
    title: "Free: Stack of Sport Aviation magazines (1998–2015)",
    description:
      "Cleaning out the hangar. Free to a good home — must take the whole stack. Local pickup only.",
    category: "free-giveaway",
    tags: ["books-manuals"],
    photos: [],
    status: "active",
    authorId: "1007",
    authorName: "Bob Tinsley",
    authorEmail: "bob.t@example.com",
    authorPhone: null,
    authorPhoneVisible: false,
    postedAt: daysAgo(5),
    expiresAt: days(55),
  },
  {
    id: "l-008",
    title: "RV-6 Project — Wings Complete",
    description:
      "RV-6 quick-build wings complete, fuselage 60% done. Includes plans, jigs, leftover materials. Health forces sale. Serious inquiries only.",
    category: "for-sale",
    tags: ["kit-build", "aircraft", "sheet-metal"],
    photos: [
      "https://images.unsplash.com/photo-1569629743817-70d8db6c323b?w=800",
      "https://images.unsplash.com/photo-1542296332-2e4473faf563?w=800",
      "https://images.unsplash.com/photo-1583500178690-f7d24c6bc40b?w=800",
    ],
    status: "expired",
    authorId: "1001",
    authorName: "Tom Becker",
    authorEmail: "tom.becker@example.com",
    authorPhone: "+1 555-201-3344",
    authorPhoneVisible: true,
    postedAt: daysAgo(95),
    expiresAt: daysAgo(5),
  },
  {
    id: "l-009",
    title: "Snap-on tool chest — gently used",
    description:
      "Snap-on roll-around tool chest, 8 drawers, very clean. Just doesn't fit my new hangar layout.",
    category: "for-sale",
    tags: ["tools"],
    photos: [],
    status: "expired",
    authorId: "1008",
    authorName: "Pat Reilly",
    authorEmail: "pat.r@example.com",
    authorPhone: null,
    authorPhoneVisible: false,
    postedAt: daysAgo(120),
    expiresAt: daysAgo(30),
  },
  {
    id: "l-010",
    title: "Misc: VFR sectional charts & E6B",
    description:
      "Various VFR sectionals (mostly Midwest), one metal E6B, and a flight bag. Make me an offer.",
    category: "miscellaneous",
    tags: ["books-manuals"],
    photos: [],
    status: "hidden",
    authorId: "1009",
    authorName: "Sam Jeffries",
    authorEmail: "sam.j@example.com",
    authorPhone: null,
    authorPhoneVisible: false,
    postedAt: daysAgo(8),
    expiresAt: days(52),
  },
];
