// Auto-generated from user-provided aviation_quotes.csv
export interface AviationQuote { text: string; author: string }

export const AVIATION_QUOTES: AviationQuote[] = [
  {"text": "Aviation is proof that given the will, we have the capacity to achieve the impossible.", "author": "Eddie Rickenbacker"},
  {"text": "Once you have tasted flight, you will forever walk the earth with your eyes turned skyward.", "author": "Leonardo da Vinci"},
  {"text": "The air is the only place free from prejudice.", "author": "Bessie Coleman"},
  {"text": "Flying might not be all plain sailing, but the fun of it is worth the price.", "author": "Amelia Earhart"},
  {"text": "The best way to predict the future is to invent it.", "author": "Alan Kay"},
  {"text": "Aviate, navigate, communicate.", "author": "Aviation adage"},
  {"text": "A good landing is one that you can walk away from.", "author": "Aviation adage"},
  {"text": "There are old pilots, and there are bold pilots, but there are no old, bold pilots.", "author": "Aviation adage"},
  {"text": "The engine is the heart of an airplane, but the pilot is its soul.", "author": "Walter Alexander Raleigh"},
  {"text": "The airplane stays up because it doesn't have time to fall.", "author": "Orville Wright"},
  {"text": "Never let an airplane take you somewhere your brain didn't get to five minutes earlier.", "author": "Unknown"},
  {"text": "Flying is the second greatest thrill known to man. Landing is the first.", "author": "Unknown"},
  {"text": "You haven't seen a tree until you've seen its shadow from the sky.", "author": "Amelia Earhart"},
  {"text": "The most difficult thing is the decision to act, the rest is merely tenacity.", "author": "Amelia Earhart"},
  {"text": "Adventure is worthwhile in itself.", "author": "Amelia Earhart"},
  {"text": "Everyone who could fly a plane in those days considered themselves an exceptional person.", "author": "Charles Lindbergh"},
  {"text": "Aviation is a demanding profession that offers rich rewards, but only for those who take it seriously.", "author": "Chuck Yeager"},
  {"text": "You don't concentrate on risks. You concentrate on results. No risk is too great to prevent the necessary job from getting done.", "author": "Chuck Yeager"},
  {"text": "It's not the plane, it's the pilot.", "author": "Unknown"},
  {"text": "To fly is heaven itself.", "author": "Wilbur Wright"},
  {"text": "The desire to fly is an idea handed down to us by our ancestors.", "author": "Wilbur Wright"},
  {"text": "It is possible to fly without motors, but not without knowledge and skill.", "author": "Wilbur Wright"},
  {"text": "If you are a lover of pure adventure, you'll never want to leave the flying game.", "author": "Charles Lindbergh"},
  {"text": "Science, freedom, beauty, adventure: what more could you ask of life? Aviation combined all the elements I loved.", "author": "Charles Lindbergh"},
  {"text": "A ship in port is safe, but that's not what ships are built for.", "author": "Grace Hopper"},
  {"text": "Man must rise above the Earth, to the top of the atmosphere and beyond, for only thus will he fully understand the world in which he lives.", "author": "Socrates"},
  {"text": "The air up there in the clouds is very pure and fine, bracing and delicious.", "author": "Wilbur Wright"},
  {"text": "Any landing you can walk away from is a good landing.", "author": "Aviation adage"},
  {"text": "Superior pilots use their superior judgment to avoid situations that require the use of their superior skill.", "author": "Aviation adage"},
  {"text": "Flying is not inherently dangerous, but to an even greater extent than the sea, it is terribly unforgiving of carelessness.", "author": "Aviation adage"},
  {"text": "Airspeed, altitude, and brains: two are always needed to successfully complete the flight.", "author": "Aviation adage"},
  {"text": "The three most useless things to a pilot: the altitude above you, the runway behind you, and a tenth of a second ago.", "author": "Aviation adage"},
  {"text": "A pilot who says he has never been frightened in an airplane is, I'm afraid, lying.", "author": "Louise Thaden"},
  {"text": "Airplanes are interesting toys but of no military value.", "author": "Marechal Ferdinand Foch"},
  {"text": "I have flown in just about everything, with just about everybody, and I have decided that airplanes may be different, but flying is pretty much the same.", "author": "Chuck Yeager"},
  {"text": "Gravity is a myth, the earth sucks.", "author": "Unknown"},
  {"text": "There is nothing quite so exhilarating as being shot at without result.", "author": "Winston Churchill"},
  {"text": "Flying is hours and hours of boredom sprinkled with a few seconds of sheer terror.", "author": "Unknown"},
  {"text": "A pilot's mind should always be working out solutions for possible alternatives.", "author": "Ernest K. Gann"},
  {"text": "The sky is not the limit. It's just a place birds fly.", "author": "Unknown"},
  {"text": "If it's not fun, you're not doing it right.", "author": "Bob Hoover"},
  {"text": "Fly it until the last piece stops moving.", "author": "Bob Hoover"},
  {"text": "Speed is life, altitude is life insurance.", "author": "Aviation adage"},
  {"text": "Sometimes the wind will blow you away, but sometimes it's the wind beneath your wings.", "author": "Unknown"},
  {"text": "Learning to fly teaches you that if you don't get your act together and adopt a serious, disciplined, safety-conscious approach, you could easily get yourself killed.", "author": "Michael Palin"},
  {"text": "The air is an extremely dangerous, jealous, and exacting mistress. Once you become enamored of her, you are hooked.", "author": "Ernest K. Gann"},
  {"text": "Oh! I have slipped the surly bonds of Earth, and danced the skies on laughter-silvered wings.", "author": "John Gillespie Magee Jr."},
  {"text": "Up, up the long, delirious, burning blue, I've topped the wind-swept heights with easy grace.", "author": "John Gillespie Magee Jr."},
  {"text": "And, while with silent, lifting mind I've trod the high untrespassed sanctity of space, put out my hand and touched the face of God.", "author": "John Gillespie Magee Jr."},
  {"text": "The air up there in the clouds is very pure and fine, bracing and delicious. And, best of all, from that flight you can never come down.", "author": "Otto Lilienthal"},
  {"text": "We are all pilots. Some of us just haven't discovered it yet.", "author": "Unknown"},
  {"text": "You know you've landed with the wheels up when it takes full power to taxi.", "author": "Aviation adage"},
  {"text": "Any pilot who relies on a single altimeter reading is asking for trouble.", "author": "Unknown"},
  {"text": "Flying is learning how to throw yourself at the ground and miss.", "author": "Douglas Adams"},
  {"text": "The only way to fly is high.", "author": "Unknown"},
  {"text": "Take off is optional. Landing is mandatory.", "author": "Aviation adage"},
  {"text": "The propeller is just a big fan in front of the plane used to keep the pilot cool. Want proof? Make it stop and watch the pilot sweat.", "author": "Unknown"},
  {"text": "There's something about the sky that keeps calling to me. Maybe it's the freedom of it.", "author": "Amelia Earhart"},
  {"text": "Never fly the 'A' model of anything.", "author": "Ed Thompson"},
  {"text": "Stay out of clouds. The silver lining everyone keeps talking about might have a very hard back to it.", "author": "Aviation adage"},
  {"text": "Keep looking around. There's always something you missed.", "author": "Aviation adage"},
  {"text": "Flying is not dangerous. Crashing is what's dangerous.", "author": "Unknown"},
  {"text": "It's easy to spot an old pilot, he's the one who has already made all the mistakes.", "author": "Aviation adage"},
  {"text": "The single most useful piece of advice I've received: keep flying the airplane.", "author": "Unknown"},
  {"text": "The Wright brothers flew through the smoke screen of impossibility.", "author": "Charles F. Kettering"},
  {"text": "If you can walk away from a landing, it's a good landing. If you can use the airplane the next day, it's an outstanding landing.", "author": "Chuck Yeager"},
  {"text": "There is no reason to fly if you're not going to have fun.", "author": "Bob Hoover"},
  {"text": "The desire to fly is beginning to whisper through their veins.", "author": "Wilbur Wright"},
  {"text": "Whoever wants to reach a distant goal must take small steps.", "author": "Antoine de Saint-Exupery"},
  {"text": "A pile of rocks ceases to be a rock pile when somebody contemplates it with the idea of a cathedral in mind.", "author": "Antoine de Saint-Exupery"},
  {"text": "The airplane has unveiled for us the true face of the earth.", "author": "Antoine de Saint-Exupery"},
  {"text": "What makes the desert beautiful is that somewhere it hides a well.", "author": "Antoine de Saint-Exupery"},
  {"text": "Perfection is achieved not when there is nothing more to add, but when there is nothing left to take away.", "author": "Antoine de Saint-Exupery"},
  {"text": "Man is not a bird, and he has no feathers, and no wings, and if he wants to fly, he ought to fall down dead.", "author": "Unknown"},
  {"text": "Once you've been in aviation for a while, flying becomes 'the norm' and you may fall into complacency.", "author": "Chesley Sullenberger"},
  {"text": "One way to fight the panic is to say to yourself: I will do the next right thing.", "author": "Chesley Sullenberger"},
  {"text": "For the first time in my life, I feel that being alive is a truly wonderful thing.", "author": "Yuri Gagarin"},
  {"text": "The Earth is blue. How wonderful. It is amazing.", "author": "Yuri Gagarin"},
  {"text": "That's one small step for man, one giant leap for mankind.", "author": "Neil Armstrong"},
  {"text": "Mystery creates wonder and wonder is the basis of man's desire to understand.", "author": "Neil Armstrong"},
  {"text": "Pilots take no special joy in walking. Pilots like flying.", "author": "Neil Armstrong"},
  {"text": "I believe every human has a finite number of heartbeats. I don't intend to waste any of mine running around doing exercises.", "author": "Neil Armstrong"},
  {"text": "If you're one percent worried about a system, it's better to talk about it than hold it inside.", "author": "Neil Armstrong"},
  {"text": "Exploration is not a choice, really, it's an imperative.", "author": "Michael Collins"},
  {"text": "Flying is freedom in its purest form, to dance with the clouds, to touch the face of God.", "author": "Unknown"},
  {"text": "The sky calls to us. If we do not destroy ourselves, we will one day venture to the stars.", "author": "Carl Sagan"},
  {"text": "Somewhere, something incredible is waiting to be known.", "author": "Carl Sagan"},
  {"text": "We are all astronauts on this spaceship called Earth.", "author": "Buckminster Fuller"},
  {"text": "Fighter pilots have ice in their veins, not blood.", "author": "Buzz Aldrin"},
  {"text": "Mars is there, waiting to be reached.", "author": "Buzz Aldrin"},
  {"text": "The view of Earth from the Moon fascinated me, a small disk, 240,000 miles away.", "author": "Buzz Aldrin"},
  {"text": "I want to see it all, I want to feel it all, I want to give everything I've got, I want to leave nothing to chance.", "author": "Sally Ride"},
  {"text": "The stars don't look bigger, but they do look brighter.", "author": "Sally Ride"},
  {"text": "Space exploration is a force of nature unto itself that no other force in society can rival.", "author": "Neil deGrasse Tyson"},
  {"text": "The nitrogen in our DNA, the calcium in our teeth, the iron in our blood, were all made in the interiors of collapsing stars.", "author": "Carl Sagan"},
  {"text": "The sky is the same everywhere, but the ground is different.", "author": "Unknown"},
  {"text": "There are three simple rules for making a smooth landing. Unfortunately, no one knows what they are.", "author": "Unknown"},
  {"text": "The only time you have too much fuel is when you're on fire.", "author": "Aviation adage"},
  {"text": "A great pilot can sail even when his canvas is rent; if his ship be dismantled, he can yet put in trim what remains of her hull and hold her to her course.", "author": "Seneca"},
  {"text": "Pilots are a rare kind of human. They leave the ordinary surface of the world to purify their soul in the sky.", "author": "Jose Maria Velasco Ibarra"}
];
