// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get-my-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  return createClient(url, key, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function notAuthed() {
  return {
    content: [{ type: "text", text: "Not authenticated" }],
    isError: true
  };
}
function errorResult(message) {
  return {
    content: [{ type: "text", text: message }],
    isError: true
  };
}
function jsonResult(data, structured) {
  return {
    content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
    structuredContent: structured ?? { data }
  };
}

// src/lib/mcp/tools/get-my-profile.ts
var get_my_profile_default = defineTool({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Get the signed-in member's roster profile from EAA Chapter 84 Connect (name, email, membership standing, expiration, aircraft, ratings).",
  inputSchema: {},
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    const email = ctx.getUserEmail();
    if (!email) return errorResult("No email in token");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("roster_members").select(
      "key_id,eaa_number,member_type,first_name,last_name,nickname,email,current_standing,expiration_date,ratings,aircraft_owned,aircraft_project,aircraft_built,preferred_city,preferred_state"
    ).ilike("email", email).maybeSingle();
    if (error) return errorResult(error.message);
    if (!data) return errorResult("No roster record found for signed-in email.");
    return jsonResult(data, { member: data });
  }
});

// src/lib/mcp/tools/list-directory.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
var list_directory_default = defineTool2({
  name: "list_directory",
  title: "List member directory",
  description: "List active EAA Chapter 84 members visible to the signed-in user. Respects each member's privacy settings and RLS.",
  inputSchema: {
    search: z.string().optional().describe("Optional case-insensitive name substring to filter by (first or last name)."),
    limit: z.number().int().min(1).max(200).optional().describe("Max rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("roster_members").select(
      "key_id,first_name,last_name,nickname,email,preferred_city,preferred_state,ratings,aircraft_owned"
    ).eq("current_standing", "Active").order("last_name").limit(limit ?? 50);
    if (search && search.trim()) {
      const s = search.trim();
      q = q.or(`first_name.ilike.%${s}%,last_name.ilike.%${s}%,nickname.ilike.%${s}%`);
    }
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return jsonResult(data ?? [], { members: data ?? [], count: data?.length ?? 0 });
  }
});

// src/lib/mcp/tools/list-hangar-talk.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
var list_hangar_talk_default = defineTool3({
  name: "list_hangar_talk_posts",
  title: "List Hangar Talk posts",
  description: "List recent Hangar Talk community posts (questions, help requests, and FYIs) from EAA Chapter 84.",
  inputSchema: {
    type: z2.enum(["question", "help", "fyi"]).optional().describe("Optional filter by post type."),
    limit: z2.number().int().min(1).max(100).optional().describe("Max rows (default 20).")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ type, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("hangar_talk_posts").select("id,type,title,body,author_key_id,last_activity_at,created_at,resolved_at").order("last_activity_at", { ascending: false }).limit(limit ?? 20);
    if (type) q = q.eq("type", type);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return jsonResult(data ?? [], { posts: data ?? [], count: data?.length ?? 0 });
  }
});

// src/lib/mcp/tools/list-classifieds.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.4.3";
var list_classifieds_default = defineTool4({
  name: "list_classifieds",
  title: "List classifieds",
  description: "List active EAA Chapter 84 classified listings (for-sale, wanted, free items).",
  inputSchema: {
    limit: z3.number().int().min(1).max(100).optional().describe("Max rows (default 20).")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("classifieds").select("id,title,description,category,tags,price,author_name,posted_at,expires_at,status").eq("status", "active").order("posted_at", { ascending: false }).limit(limit ?? 20);
    if (error) return errorResult(error.message);
    return jsonResult(data ?? [], { classifieds: data ?? [], count: data?.length ?? 0 });
  }
});

// src/lib/mcp/tools/list-volunteering.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^4.4.3";
var list_volunteering_default = defineTool5({
  name: "list_volunteering_opportunities",
  title: "List volunteering opportunities",
  description: "List active EAA Chapter 84 volunteering opportunities members can sign up for.",
  inputSchema: {
    limit: z4.number().int().min(1).max(100).optional().describe("Max rows (default 20).")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("volunteering_opportunities").select("id,title,description,num_volunteers,status,created_by_name,created_at").eq("status", "active").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) return errorResult(error.message);
    return jsonResult(data ?? [], { opportunities: data ?? [], count: data?.length ?? 0 });
  }
});

// src/lib/mcp/index.ts
var projectRef = "exhrqwxmezowohckuzvv";
var mcp_default = defineMcp({
  name: "eaa84-connect-mcp",
  title: "EAA Chapter 84 Connect",
  version: "0.1.0",
  instructions: "Tools for EAA Chapter 84 Connect. Callers act as their signed-in member account. Use get_my_profile for membership status, list_directory to look up members, and list_hangar_talk_posts / list_classifieds / list_volunteering_opportunities for chapter activity.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_my_profile_default, list_directory_default, list_hangar_talk_default, list_classifieds_default, list_volunteering_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
